# -*- coding: utf-8 -*-
"""Order List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f35eJ3T75w4XuCUN1gLx_K51BP4U5yZq
"""

class OrderList:

    def __init__(self, initial_elements=[]):
        self.elements = []

    def __str__(self):
        return str(self.elements)

    def __len__(self):
        return len(self.elements)

    def __getitem__(self, index):
        try:
            return self.elements[index]
        except IndexError:
            print("Error: Índice fuera de rango.")

    def isEmpty(self):
        return len(self.elements) == 0

    def __iter__(self):
        for element in self.elements:
            yield element

    def __contains__(self, element):
        return element in self.elements

    def binary_search(self, element): # Búsqueda Binaria
        left, right = 0, len(self.elements)

        while left < right:
            middle = (left + right) // 2

            if self.elements[middle] < element:
                left = middle + 1
            else:
                right = middle
        return left

    def add(self, element):
        position = self.binary_search(element)
        #print(position)
        self.elements.insert(position, element)

    def remove(self, element):
        try:
            position = self.binary_search(element)

            if position < len(self.elements) and self.elements[position] == element:
                self.elements.pop(position)
            else:
                print(f"Error: Elemento {element} no encontrado.")

        except Exception as e:
            print(f"Error: {e}.")

    def pop(self, index):
        try:
            return self.elements.pop(index)
        except IndexError:
            print("Error: Índice fuera de rango.")

    def clear(self):
        self.elements.clear()

"""Prueba:"""

lista = OrderList()

lista.add("A")
lista.add("B")
lista.add("Z")
lista.add("O")
lista.add("F")

print(lista)
print("W" in lista)

lista.pop(20)

print(lista)
print("")
print(lista.__getitem__(10))
print("")

lista.remove("Y")
lista.add("K")
lista.add("G")
lista.add("W")

print(lista)

iter(lista)

for elemento in lista:
    print(" - ", elemento)

lista.pop(3)
print(lista)
print(lista.isEmpty())
lista.clear()
print(lista.isEmpty())