# -*- coding: utf-8 -*-
"""Stack

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KaouGvggnAw42WJARH-z0wtkfDlvt6YS
"""

class Stack:

    def __init__(self, initial_elements=[]):
        self.elements = []

    def __str__(self):
        return str(self.elements)

    def __len__(self):
        return len(self.elements)

    def isEmpty(self):
        return len(self.elements) == 0

    def peek(self):
        if self.isEmpty():
            raise IndexError("Pila vacía")
        return self.elements[-1]

    def __iter__(self):
        for element in self.elements:
            yield element

    def __contains__(self, element):
        return element in self.elements

    def push(self, element):
        self.elements.append(element)

    def pop(self, index=-1):
        if self.isEmpty():
            raise IndexError("Pila vacía")
        return self.elements.pop(index)

lista = Stack()

lista.push("A")
lista.push("B")
lista.push("Z")
lista.push("O")
lista.push("F")

print(lista)
lista.pop()
print(lista)
print(lista.peek())