# -*- coding: utf-8 -*-
"""Circular List

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QI6PgDd61YFrgRTkbYGFYeernlYI7eS
"""

class Node:
    def __init__(self, value):
        self.value = value
        self.next = None

class CircularList:
    def __init__(self, initial_elements=None):
        self.head = None
        self.tail = None
        self.size = 0
        if initial_elements:
            for element in initial_elements:
                self.append(element)

    def __str__(self):
        return str(list(self))

    def __len__(self):
        return self.size

    def __getitem__(self, index):
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")
        current = self.head
        for i in range(index):
            current = current.next
        return current.value

    def isEmpty(self):
        return self.size == 0

    def __iter__(self):
        if self.isEmpty():
            return
        current = self.head
        for i in range(self.size):
            yield current.value
            current = current.next

    def __contains__(self, element):
        if self.isEmpty():
            return False
        current = self.head
        for i in range(self.size):
            if current.value == element:
                return True
            current = current.next
        return False

    def append(self, element):
        new_node = Node(element)
        if self.size == 0:
            self.head = new_node
            self.tail = new_node
            new_node.next = new_node
        else:
            new_node.next = self.head
            self.tail.next = new_node
            self.tail = new_node
        self.size += 1

    def _get_node(self, index):
        current = self.head
        for i in range(index):
            current = current.next
        return current

    def add(self, index, element):
        if index < 0 or index > self.size:
            raise IndexError("Índice fuera de rango")

        if index == self.size:
            self.append(element)
            return

        new_node = Node(element)
        if index == 0:
            if self.size == 0:
                self.head = new_node
                self.tail = new_node
                new_node.next = new_node
            else:
                new_node.next = self.head
                self.head = new_node
                self.tail.next = self.head
        else:
            prev = self._get_node(index - 1)
            new_node.next = prev.next
            prev.next = new_node
        self.size += 1

    def remove(self, element):
        if self.isEmpty():
            raise ValueError("Error: Lista vacía.")

        if self.head.value == element:
            if self.size == 1:
                self.head = None
                self.tail = None
            else:
                self.head = self.head.next
                self.tail.next = self.head
            self.size -= 1
            return

        prev = self.head
        current = self.head.next
        for i in range(self.size - 1):
            if current.value == element:
                prev.next = current.next
                if current == self.tail:
                    self.tail = prev
                self.size -= 1
                return
            prev = current
            current = current.next

        raise ValueError("Error: Elemento no encontrado.")

    def pop(self, index):
        if index < 0 or index >= self.size:
            raise IndexError("Índice fuera de rango")

        if index == 0:
            value = self.head.value
            if self.size == 1:
                self.head = None
                self.tail = None
            else:
                self.head = self.head.next
                self.tail.next = self.head
            self.size -= 1
            return value

        prev = self._get_node(index - 1)
        value = prev.next.value
        if prev.next == self.tail:
            self.tail = prev
        prev.next = prev.next.next
        self.size -= 1
        return value

    def clear(self):
        self.head = None
        self.tail = None
        self.size = 0

lista = CircularList()

lista.append("A")
lista.append("B")
lista.append("C")
lista.append("D")
lista.append("E")
print(lista)

lista.append("Z")
print(lista)

lista.add(1, "Y")
print(lista)
print(lista.__getitem__(3))

lista.remove("A")
print(lista)
lista.pop(0)
print(lista)

lista.clear()
print(lista)